- name: Apt-get update
  apt:
    update_cache: yes

- name: install packages
  apt:
    pkg:
        - dnsmasq

- name: Enable and restart dnsmasq service
  service:
    name: dnsmasq
    enabled: yes

- name: Create dnsmasq configuration
  copy:
    src: 10-consul
    dest: /etc/dnsmasq.d/

- name: Restart dnsmasq service
  service:
    name: dnsmasq
    state: restarted