- name: remove apt locak file
  file:
    state: absent
    path: /var/lib/dpkg/lock

- name: install packages
  apt:
    update_cache: yes
    pkg:
        - dnsmasq

- name: Enable and restart dnsmasq service
  service:
    name: dnsmasq
    enabled: yes

- name: Create dnsmasq configuration
  copy:
    src: 10-consul
    dest: /etc/dnsmasq.d/

- name: Restart dnsmasq service
  service:
    name: dnsmasq
    state: restarted