variable "consul_number_of_server" {}
variable "instance_type" {}
variable "tag_enviroment" {}
variable "project_name" {}
variable "vpc_id" {}
variable "ami_id" {}
variable "key_name" {}
variable "iam_instance_profile" {}
variable "private_subnet_id" {}
variable "jenkins_security_group_id" {}
variable "alb1_security_group_id" {}