- name: Create jenkins user and group
  user:
      name: jenkins
      state: present

- name: create jenkins folder 
  file:
    path: /var/jenkins
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0775'
