- name: ensure jenkins is installed
  apt: 
    name: jenkins

- name: Replace jenkins port
  lineinfile:
    path: /lib/systemd/system/jenkins.service
    regexp: 'Environment="JENKINS_PORT=8080"'
    line: Environment="JENKINS_PORT={{ jenkins_ui_port }}"

- name: disable wizard
  lineinfile:
    path: /lib/systemd/system/jenkins.service
    regexp: 'Environment="JAVA_OPTS=-Djava.awt.headless=true"'
    line: Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"

- name: copy csca xml describe path configuration
  template:
    src: casc_path.j2
    dest: /var/lib/jenkins/io.jenkins.plugins.casc.CasCGlobalConfig.xml

- name: copy csca configuration
  template:
    src: casc.j2
    dest: /var/lib/jenkins/casc.yaml
    

- name: Reload service
  systemd:
    daemon_reload: yes

- name: ensure jenkins is running
  service: 
      name: jenkins
      state: restarted
      enabled: yes