variable "instance_type" {}
#variable "availability_zone" {}
variable "private_subnet_id" {}
variable "tag_enviroment" {}
variable "project_name" {}
variable "vpc_id" {}
variable "ami_id" {}
variable "key_name" {}
variable "iam_instance_profile" {}
#variable "private_key_file_name" {}