variable "instance_type" {}
variable "private_subnet_id" {}
variable "tag_enviroment" {}
variable "project_name" {}
variable "vpc_id" {}
variable "ami_id" {}
variable "key_name" {}
variable "iam_instance_profile" {}
variable "ansible_number_of_servers" {}