variable "jenkins_nodes_number_of_server" {}
variable "tag_enviroment" {}
variable "project_name" {}
variable "vpc_id" {}
variable "jenkins_server_ami_id" {}
variable "jenkins_client_ami_id" {}
variable "key_name" {}
variable "iam_instance_profile" {}
variable "private_subnet_id" {}
variable "jenkins-node-instance-type" {}
variable "jenkins-server-instance-type" {}
variable "alb1_security_group_id" {}
variable "jenkins_master_number_of_servers" {}
variable "aws_region" {}
variable "eks_cluster_name" {}
variable "is_consul_server" {}