---
- name: apt-get update
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install a list of packages  - ubuntu
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  when: ansible_os_family == "Debian"

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker Repository - ubuntu
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  when: ansible_os_family == "Debian"

- name: Install docker - ubuntu
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli 
      - containerd.io
  notify:
      - restart docker
  when: ansible_os_family == "Debian"

- name: Add Docker Repository - Redhat
  yum_repository:
    name: docker-repo
    description: "repo for docker"
    baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
    enabled: yes
    gpgcheck: no
  when: ansible_os_family == "RedHat"

- name: Install packages  - Redhat
  yum:
    name: "{{item}}"
    state: latest
  with_items:
    - python3
  when: ansible_os_family == "RedHat"

- name: Install pip
  pip:
    name: "{{item}}"
    executable: pip3.6
  with_items:
    - docker
  when: ansible_os_family == "RedHat"

- name: Install docker - redhat
  package:
    name: docker-ce-18.09.1-3.el7.x86_64
    state: latest
  when: ansible_os_family == "RedHat"

- name: service restart
  service:
    name: docker
    state: restarted
    enabled: yes
  when: ansible_os_family == "RedHat"
  # notify:
  #     - restart docker
  # when: ansible_os_family == "RedHat"
