- hosts: _role_jenkins_node
  remote_user: ubuntu
  vars:
    eks_cluster_name: "{{ lookup('env','EKS_CLUSTER_NAME') }}"
    aws_region: "{{ lookup('env','AWS_REGION') }}"
    consul_server: "false"
    #consul_version: "1.11.4"    
    #consul_dc_name: mid-project
  become: yes
  tasks:
    - name: Install baseline pack (Consul,node-exporter)
      include_role:
        name: baseline-pack

    - name: Install prerequsites for jenkins node
      include_role:
        name: jenkins-node

    - name: run docker installation
      include_role:
        name: docker
    
    - include: register-service.yml
      vars:
          service_registration: 
            - jenkins-node
    
    - name: Install trivy
      include_role:
        name: trivy-docker-scan
      vars:
        trivy_version: "0.23.0"

    - name: update kubectl configuration
      shell: aws eks update-kubeconfig --region {{ aws_region }} --name {{ eks_cluster_name }}
      become: no