- hosts: _role_jenkins_server
  remote_user: ubuntu
  become: yes
  vars:
    jenkins_ui_port: 9000
    alb_dns: alb1-2056122047.us-east-1.elb.amazonaws.com
  tasks:

    - name: Install consul agent
      include_role:
        name: consul-agent
      vars:
        consul_version: "1.11.4"
        consul_dc_name: mid-project

    - name: run jenkins-server
      include_role:
        name: jenkins-server

    # - name: Verify jenkins server private ip
    #   uri:
    #     url: http://169.254.169.254/latest/meta-data/local-ipv4
    #     return_content: yes
    #   register: ec2_private_ip

    # - name: show jenkins servers private ip
    #   debug:
    #     msg: jenkins server private ip - {{ ec2_private_ip.content }}

    - name:
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: admin_code
    
    - debug:
        msg: Enter the following id for UI login {{admin_code.stdout}}
   
    - debug:
        msg: Jenkins sever is running on port {{ jenkins_ui_port }}

    - name: install plugin
      delegate_to: localhost
      shell: java -jar ./files/jenkins-cli.jar -auth admin:{{admin_code.stdout}} -s http://{{ alb_dns }}:{{ jenkins_ui_port }} -webSocket install-plugin {{ item }}
      with_items:
        - github-branch-source:latest
        - workflow-aggregator:latest
        - ssh-slaves:latest
        - docker-workflow:latest
        - docker-plugin:latest
        - configuration-as-code:latest

    - name: restart jenkins
      delegate_to: localhost
      shell: java -jar ./files/jenkins-cli.jar -auth admin:{{admin_code.stdout}} -s http://{{ alb_dns }}:{{ jenkins_ui_port }} -webSocket restart
