- hosts: _role_jenkins_server
  remote_user: ubuntu
  become: yes
  vars:
    jenkins_ui_port: 9000
    webhook_key: "6be78799-a6ff-4649-aba2-3dddfcd37d17"
    webhook_secret: "Lwo0NQFAtO15"
  tasks:

    - name: Install consul agent
      include_role:
        name: consul-agent
      vars:
        consul_version: "1.11.4"
        consul_dc_name: mid-project

    - name: run jenkins-server
      include_role:
        name: jenkins-server


    - name: Verify jenkins server private ip
      uri:
        url: http://169.254.169.254/latest/meta-data/local-ipv4
        return_content: yes
      register: jenkins_private_ip

    - name:
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: admin_code
    
    - debug:
        msg: Enter the following id for UI login {{admin_code.stdout}}
   
    - debug:
        msg: Jenkins sever is running on port {{ jenkins_ui_port }}

    - name: copy cli tool
      copy:
        src: ./files/jenkins-cli.jar
        dest: /home/ubuntu/jenkins-cli.jar

    - name: install plugin
      shell: java -jar /home/ubuntu/jenkins-cli.jar -auth admin:{{admin_code.stdout}} -s http://{{ jenkins_private_ip.content }}:{{ jenkins_ui_port }} -webSocket install-plugin {{ item }}
      with_items:
        - github-branch-source:latest
        - workflow-aggregator:latest
        - ssh-slaves:latest
        - docker-workflow:latest
        - docker-plugin:latest
        - configuration-as-code:latest
        - dockerhub-notification:latest

    - name: restart jenkins server 
      service: 
        name: jenkins
        state: restarted

    # - name: restart jenkins
    #   shell: java -jar /home/ubuntu/jenkins-cli.jar -auth admin:{{admin_code.stdout}} -s http://{{ jenkins_private_ip.content }}:{{ jenkins_ui_port }} -webSocket restart

    # - name: create webhook file
    #   copy:
    #     dest: /opt/webhook-client.sh
    #     content: |
    #       relay login -k{{ webhook_key }} -s {{ webhook_secret }}