- name: Create Consul user and group
  user:
      name: consul
      state: present


- name: install packages
  apt:
    pkg:
        - dnsmasq
  when: ansible_distribution_major_version == "18"

- name: Enable and restart dnsmasq service
  service:
    name: dnsmasq
    enabled: yes
  when: ansible_distribution_major_version == "18"

- name: Create dnsmasq configuration
  copy:
    src: 10-consul
    dest: /etc/dnsmasq.d/
  when: ansible_distribution_major_version == "18"

- name: Restart dnsmasq service
  service:
    name: dnsmasq
    state: restarted
  when: ansible_distribution_major_version == "18"


- name: Create systemd-resolved configuration
  copy:
    src: resolved.conf
    dest: /etc/systemd/


- name: Restart systemd-resolved service
  service:
    name: systemd-resolved.service
    state: restarted


- name: Create folder for consul
  file:
    path: "{{ item }}"
    state: directory
    owner: consul
    group: consul
  with_items:
    - /opt/consul
    - /etc/consul.d
    - /run/consul
  when: 'consul_version not in consul_version_output.stdout'

- name: download consul file
  get_url:
    url: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
    dest: /tmp
  register: file
  when: 'consul_version not in consul_version_output.stdout'

- debug:
    msg: downloaded file - {{ file.dest }}
  when: 'consul_version not in consul_version_output.stdout'

- name: unzip consul
  unarchive:
    src: "{{ file.dest }}"
    dest: /usr/local/bin/
    owner: consul
    group: consul
    remote_src: yes
  when: 'consul_version not in consul_version_output.stdout'


- name: Verify ec2-private-ip
  uri:
    url: http://169.254.169.254/latest/meta-data/local-ipv4
    return_content: yes
  register: ec2_private_ip


- name: copy consul-server config file
  template:
    src: consul-server-config.j2
    dest: /etc/consul.d/config.json
  when: consul_server == "true"

- name: copy consul-agent config file
  template:
    src: consul-agent-config.j2
    dest: /etc/consul.d/config.json
  when: consul_server == "false"

- name: Create consul service
  copy:
    src: consul.service
    dest: /etc/systemd/system/
  when: 'consul_version not in consul_version_output.stdout'

- name: Reload service
  systemd:
    daemon_reload: yes
  when: 'consul_version not in consul_version_output.stdout'

- name: Enable consul service
  service:
    name: consul
    enabled: yes
  when: 'consul_version not in consul_version_output.stdout'

- name: Restart consul service
  service:
    name: consul
    state: restarted

- name: Verify consul server private ip
  uri:
    url: http://169.254.169.254/latest/meta-data/local-ipv4
    return_content: yes
  register: ec2_private_ip

- name: show consul servers private ip
  debug:
    msg: consul server private ip - {{ ec2_private_ip.content }}
