global:
  enabled: false
  image: "hashicorp/consul:1.11.4"
  datacenter: mid-project
  gossipEncryption:
    secretName: consul-gossip-key
    secretKey: key

client:
  enabled: true
  join:
    - "provider=aws tag_key=consul_server tag_value=true"
  nodeMeta:
      pod-name: ${HOSTNAME}
      host-ip: ${HOST_IP}
  exposeGossipPorts: true
dns:
  enabled: true

syncCatalog:
  enabled: true